name: Publish

on: 
  push:
    branches:
      - fix
  pull_request:
    types:
      - closed
    branches:
      - dev
      - main
   
jobs:
  publish:
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: node
       uses: actions/setup-node@v3
       with:
         node-version: 18
         registry-url: https://registry.npmjs.org
     - name: install node
       run: npm install
     - name: debug
       run: echo ${{ github.head_ref }}
     - name: major version
       if: ${{ github.head_ref == 'refs/heads/main' }}
       run: npm version major
     - name: minor version
       if: ${{ github.head_ref == 'refs/heads/dev' }}
       run: npm version minor   
     - name: patch version
       if: github.ref == 'refs/heads/fix'
       run: npm version patch --no-git-tag-version 
     - name: publish
       if: github.event.pull_request.merged == true
       run: npm publish --access public
       env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}